#+title:Jazz Piano Tutorial
This is a tutorial for myself. I started the tutorial as a newbie of jazz piano players.

The material is limited to a 32-key MIDI controller and a computer, as perfect much as what I have got.

I divided the how [[id:32570108-B834-48D2-B439-187626176C73][Jazz Piano machine]] mainly into harmony, melody and rhythm.

This is not a start-from-scratch tutorial, the kind I usually recommand, but rather a index of drills I collected from various of resources. In this paradigm, the 3 aspects below are the base class/categories of elements one should consider in a jazz piano playing session. They can also be seen as attributes of charactor in RPG like DEF, ATK, or AGI, whereas practicing the drills would increase the value of the attributes.
* Harmony
** Block chord
** Upper Structure
** Evenly spaced Scale
1st, 3rd and 7th from D Dorian.
or 2nd, 5th, 7th, 12th, 13th from D Dorian.



* Melody
the percpectives below could be considered:
** Scales
Scales could be chosen according to current chord or current tone(consisting bunch of chords).

Use scale as available set of notes.
*** Kinds of scales
*** Perspective: Combination of half step chunks and whole step chunks
Scale could be viewed as combination of chunks of half/whole step.

For example, a Major scale could be viewed as 123 4567, grouped to 2 chunks of whole steps, while a dorian could be viewed as 12 3456 7.

As the pattern of whole step is easy on keyboard, this view provide an easy way to walk through scales with less calculation.

*** Using scale
**** Switching scales
Switch from one scale to another could make the sound a lot different and messed up your freind watching you playing as you're playing almost all of the 12 notes in an octave.

This could be practiced by simply improvising on scale A for 4 bar and on scale B for 4 bar right after.

** Positions
You'll need at least 3 positions on each scale: thumb at 1st, 4th and 6th.
The minimal is 1st and 4th, which is the way your playing through the scale.

While you're playing, you're not likely to move your hand around without reason. So the positions often used could be a entrance for further improvisation. A simple lick could do.

Position could also be a way to remember the scale.
** Bebop licks
Practice licks from bebop

*** Basic structure
Enclosure and approching on every scale could be practiced.

This could be practiced by conducting structure and apply it to every note on a particular scale. It could be in a Hannon manner, from Do , Re to Ti; or follow the order of arppegio; or other order of choice.
*** Famous/Favor licks
Could transform licks heard from pieces of sounds to structure applying to every scale and note position.

For example, a 2345312 lick could be placed on:
+ C major scale, starting from D
+ C major scale, starting from E(could be argued of being in D Dorian scale)
+ C Dorian scale, starting from D
+ C Dorian Scale, starting from Eb
+ D major scale, starting from E

Note that the second way above could also be seen as in D Dorian scale, but thinking it as starting from II of C major scale would have the benefit of applying the lick everywhere on scale, without too much thinking.

The exercise regarding licks have a goal to familiar both hand and ear, and majorly ear. Every piano player can play a lot of phrases, like a piece of Chopin or Beethoven, and it's of little difficulty. Being able to have the phrases pop up in your ear and make the order to play the phrace to your hand means that you can use the phrace to enrich your vocabulary.

* Rhythm
* Tasks
** TODO Get task/workshop/practice for each drill

